# Generated by Django 5.1.5 on 2025-02-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0004_alter_player_height_alter_player_salary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="standings",
            options={"ordering": ["-win_percentage"]},
        ),
    ]
