# Generated by Django 5.1.5 on 2025-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0005_alter_standings_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="player",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
