# Generated by Django 5.1.5 on 2025-02-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bba_stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="height",
            field=models.FloatField(),
        ),
    ]
