# Generated by Django 5.1.5 on 2025-02-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bba_stats", "0002_alter_player_height"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("home_team", models.CharField(max_length=100)),
                ("away_team", models.CharField(max_length=100)),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Standings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team", models.CharField(max_length=100, unique=True)),
                (
                    "conference",
                    models.CharField(
                        choices=[("East", "East"), ("West", "West")], max_length=10
                    ),
                ),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("win_percentage", models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.AlterModelOptions(
            name="player",
            options={"ordering": ["id"]},
        ),
    ]
